# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Form(QtWidgets.QWidget):
    def setupUi(self):
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setObjectName("self")
        self.resize(721, 501)
        self.setStyleSheet("")
        self.main = QtWidgets.QWidget(self)
        self.main.setGeometry(QtCore.QRect(0, 0, 721, 501))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.main.setFont(font)
        self.main.setStyleSheet("""
        QFrame#titleBar {
                background-color: #14171A;
                border: 4px solid #657786;
                border-radius: 5px
                }
        
        QFrame#frame{
                background-color: #1DA1F2;
                border: 5px solid #14171A;
                border-top: 0
                }
                
        QPushButton#close{
                border:3px solid #AAB8C2;
                border-radius: 5px;
                color: red
                }
        
        QPushButton#minimize {
                border:3px solid #AAB8C2;
                border-radius: 5px;
                color: green;
                }
        
        QPushButton#minimize::hover, QPushButton#close::hover  {
                border:3px solid #F5F8FA;
                background-color: rgb(30, 34, 39);
                border-top: 10 px;
                border-left: 10 px;
                padding-top: 10px
                }
        
        QPushButton#send {
                background-color: #14171A;
                color: #F5F8FA;
                border-radius: 10px;
                border-top-left-radius: 0;
                border-bottom-left-radius: 0;
                }
        
        QPushButton#send::hover {
                background-color: #657786;
                padding-left: 10px
                }
                
        QPlainTextEdit#tweetCont {
                background-color: #E1E8ED;
                color: #657786;
                border-top-right-radius: 40px;
                border: 0;
                }
        
        QWidget#scroll {
                background-color: transparent;
        	border-bottom: 3px solid white
        }
        
        QScrollArea {
                background-color: transparent;
                border: 0;
                border-radius: 0
        }

        QTextBrowser {
                background-color: #E1E8ED;
                color: #657786;
                border: 0;
                border-bottom: 5px solid #14171A;
                border-top-left-radius: 10px;
                font: 18pt Nirmala UI;
                }""")
        self.main.setObjectName("main")
        self.titleBar = QtWidgets.QFrame(self.main)
        self.titleBar.setGeometry(QtCore.QRect(0, 0, 721, 71))
        self.titleBar.setStyleSheet("")
        self.titleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.title = QtWidgets.QLabel(self.titleBar)
        self.title.setGeometry(QtCore.QRect(100, 10, 231, 51))
        self.title.setStyleSheet("color: #E1E8ED;\n"
"font: 75 14pt \"Orbitron\";\n"
"border: 0")
        self.title.setObjectName("title")
        self.logo = QtWidgets.QLabel(self.titleBar)
        self.logo.setGeometry(QtCore.QRect(10, 0, 71, 71))
        self.logo.setStyleSheet("border:0")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("scripts/appIntreface/twitterBlockChain.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.close = QtWidgets.QPushButton(self.titleBar)
        self.close.setGeometry(QtCore.QRect(660, 20, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.close.setFont(font)
        self.close.setStyleSheet("")
        self.close.setObjectName("close")
        self.minimize = QtWidgets.QPushButton(self.titleBar)
        self.minimize.setGeometry(QtCore.QRect(600, 20, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.minimize.setFont(font)
        self.minimize.setObjectName("minimize")
        self.frame = QtWidgets.QFrame(self.main)
        self.frame.setGeometry(QtCore.QRect(0, 70, 721, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.send = QtWidgets.QPushButton(self.frame)
        self.send.setGeometry(QtCore.QRect(610, 370, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.send.setFont(font)
        self.send.setObjectName("send")
        self.tweetCont = QtWidgets.QPlainTextEdit(self.frame)
        self.tweetCont.setGeometry(QtCore.QRect(13, 340, 601, 81))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(19)
        self.tweetCont.setFont(font)
        self.tweetCont.setPlainText("")
        self.tweetCont.setObjectName("tweetCont")
        
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(10, 0, 701, 341))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName('scroll')
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 682, 404))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(130, 100, 461, 321))
        self.frame.setStyleSheet("""
        QFrame#frame {
                background: #14171A
                }
        
        QTabWidget::pane {
                border: 1px solid white;
                border-top: 0;
                background-color: #14171A
                }
        
        QTabBar::tab{
                background-color: #1DA1F2;
                color: #F5F8FA;
                border-radius: 5px;
                width: 218px;
                height: 30px;
                font: 75 14pt Rockwell bold;
                }
        
        QTabBar::tab:!selected {
                background-color: #14171A;
                color: #1DA1F2;
                border: 1px solid #1DA1F2;
                }
        
        QTabBar::tab:!selected:hover {
                background-color:rgb(8, 46, 68);
                }
                
        QLineEdit {
                background-color: transparent;
                color: #F5F8FA;
                border: 1px solid #657786;
                border-radius: 10px
                }
                
        QLineEdit#account{
                border-top-right-radius: 0px;
                border-bottom-right-radius: 0px;
                }
        
        QLineEdit:focus {
                border-color: #1DA1F2
                }
        
        QPushButton {
                background-color: #1DA1F2;
                color: #F5F8FA;
                border: #E1E8ED;
                border-radius: 15px;
                font: 75 14pt Rockwell bold;
                }
        
        QPushButton#browse {
                border-top-left-radius: 0;
                border-bottom-left-radius: 0;
                }
                
        QPushButton::hover {
                background: rgb(22, 129, 191);
                padding-top: 10px
                }
        
        QPushButton#browse::hover {
                padding:0;
                padding-left: 10px;
                }
        
        QLabel#login_label, QLabel#sing_label {
                color: rgb(54, 62, 70);
                font: 75 14pt "Orbitron";
                }
        
        QLabel#login_label::hover, QLabel#sing_label::hover {
                color: rgb(78, 90, 102)
                }
        """)

        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.log_in = QtWidgets.QWidget()
        self.log_in.setObjectName("log_in")
        self.login_label = QtWidgets.QLabel(self.log_in)
        self.login_label.setGeometry(QtCore.QRect(100, 20, 211, 51))
        self.login_label.setObjectName("login_label")
        self.account = QtWidgets.QLineEdit(self.log_in)
        self.account.setGeometry(QtCore.QRect(30, 70, 261, 31))
        self.account.setObjectName("account")
        self.submit_in = QtWidgets.QPushButton(self.log_in)
        self.submit_in.setGeometry(QtCore.QRect(160, 150, 111, 31))
        self.submit_in.setObjectName("submit_in")
        self.browse = QtWidgets.QPushButton(self.log_in)
        self.browse.setGeometry(QtCore.QRect(290, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.browse.setFont(font)
        self.browse.setObjectName("browse")
        self.tabWidget.addTab(self.log_in, "")
        self.sing_up = QtWidgets.QWidget()
        self.sing_up.setObjectName("sing_up")
        self.sing_label = QtWidgets.QLabel(self.sing_up)
        self.sing_label.setGeometry(QtCore.QRect(100, 50, 211, 51))
        self.sing_label.setObjectName("sing_label")
        self.name = QtWidgets.QLineEdit(self.sing_up)
        self.name.setGeometry(QtCore.QRect(80, 110, 261, 31))
        self.name.setObjectName("name")
        self.submit_up = QtWidgets.QPushButton(self.sing_up)
        self.submit_up.setGeometry(QtCore.QRect(150, 170, 111, 31))
        self.submit_up.setObjectName("submit_up")
        self.tabWidget.addTab(self.sing_up, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.send.setDisabled(True)
        self.tweetCont.setDisabled(True)

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def closeEvent(self, event):
            event.ignore()

    def addTweet(self, _name, _date, _tweet):
        
        name_style = """
        QLabel#name {
                background-color: #14171A;
                color: #F5F8FA;
                font: 12pt "Russo One";
                border: 0
                }
        
        QLabel#name::hover {
                color: rgba(225, 232, 237, 150);
                text-decoration: underline
                }
        """

        date_style = """
        QLabel#date {
                background-color: #14171A;
                color: #AAB8C2;
                font: 12pt "Russo One";
                border: 0;
                }

        QLabel#date::hover {
                color: rgba(225, 232, 237, 150);
                text-decoration: underline
                }
        """
        gridLayout = QtWidgets.QGridLayout()
        
        name = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        name.setStyleSheet(name_style)
        name.setObjectName('name')
        name.setText(_name)
        name.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        name.setFont(font)
        gridLayout.addWidget(name, 0, 0, 1, 2)
        
        date = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        date.setObjectName('date')
        date.setText(_date)
        date.setStyleSheet(date_style)
        date.setGeometry(QtCore.QRect(10, 50, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(10)
        date.setFont(font)
        gridLayout.addWidget(date, 1, 0, 1, 1)

        content = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        content.setText(_tweet)
        content.setGeometry(QtCore.QRect(120, 20, 361, 221))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        content.setFont(font)
        gridLayout.addWidget(content, 1, 1, 2, 1)
        
        self.verticalLayout.addLayout(gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "BlockChainTwitter"))
        self.close.setText(_translate("Form", "X"))
        self.close.setShortcut(_translate("Form", "Ctrl+W"))
        self.minimize.setText(_translate("Form", "_"))
        self.send.setText(_translate("Form", "Tweet"))
        self.tweetCont.setPlaceholderText(_translate("Form", "what\'s happening?"))
        self.account.setPlaceholderText(_translate("Form", "Account file path..."))
        self.submit_in.setText(_translate("Form", "Submit"))
        self.browse.setText(_translate("Form", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log_in), _translate("Form", "Log in"))
        self.name.setPlaceholderText(_translate("Form", "Name"))
        self.submit_up.setText(_translate("Form", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sing_up), _translate("Form", "Sign up"))
        self.login_label.setText(_translate("Form", "BlockChainTwitter"))
        self.sing_label.setText(_translate("Form", "BlockChainTwitter"))